### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by jonathandavidlewis** [riftrid3r/js-linked-list#20]
@riftrid3r 
Looks like the code could use a cleanup.
The add function is adjacent to 'start' and 'end' so it blends in a bit.  The spacing on the other methods is helpful.

Also, could use some lining.  Here's an example:

```javascript
  this.add=function(data) {
    if (this.start===null) {
      this.start=List.makeNode();
      this.end=this.start;
    } else {
      this.end.next=List.makeNode();
      this.end=this.end.next();
    }
    this.end.data=data;
    };
```

**Comment by riftrid3r** [comment]
I agree.
